### ISSUE TITLE
Typo on glossary

### ISSUE THREAD

**Issue by elsatch** [libreobjet/open-guide#1]
Hi,

I was reviewing the glossary and discovered a typo. I imagine you're talking about MAKE: or Make magazine, not Maker Magazine :)

**Comment by xuv** [comment]
Ha. I don't know Maker Magazine. Do you have a link?

**Update**: Ho, I get it. Still a bit early. :) Will be solved in following commit :)

**Comment by xuv** [comment]
Solved in commit b0a613d810fdb895ee5d3b7e834075239a71586b Thx for the heads up :)
