### ISSUE TITLE
Cebuano Localization

### ISSUE THREAD

**Issue by jbeguna04** [libreobjet/open-guide#21]
Hi Good Day! I would like to request to contribute in your project. Please allow me to have translation in Cebuano. Hoping for your positive response!
Thank You!

**Comment by xuv** [comment]
Hello @jbeguna04. Thanks for your message and for your proposition to translate in Cebuano. We gladly appreciate all contributions. So you are definitely welcoming a translation in Cebuano. Though I will definitely not be able to help you with it :)

But please, make a pull request once you have a page translated.

We need help to translate the book in Portuguese.

This list is here to keep track of the pages that still need translation and proof reading.

### Translation status:
- [ ] GLOSSARY.md
- [ ] LICENSE.md
- [ ] README.md
- [ ] SUMMARY.md
- [ ] design_process.md
- [ ] distribution.md
- [ ] economies.md
- [ ] introduction.md
- [ ] licenses.md
- [ ] motivation.md
- [ ] proposition.md
- [ ] this_book.md

### Proof read status
- [ ] GLOSSARY.md
- [ ] LICENSE.md
- [ ] README.md
- [ ] SUMMARY.md
- [ ] design_process.md
- [ ] distribution.md
- [ ] economies.md
- [ ] introduction.md
- [ ] licenses.md
- [ ] motivation.md
- [ ] proposition.md
- [ ] this_book.md

**Comment by jbeguna04** [comment]
where can i translate the files? PLease help

**Comment by xuv** [comment]
All the original english files are in the `en` folder.
I've just created the `ceb` folder for the Cebuano language. The idea is that you choose an english file from the `en` folder then copy and translate its content in a file in the `ceb` folder.
I've already copied the GLOSSARY.md file. You can start with that. To edit it, click the pencil icon on the top of the page and save it.
For detail info on editing files, check [Github documentation](https://help.github.com/articles/editing-files-in-another-user-s-repository/).
Let me know how that works for you.

**Comment by jbeguna04** [comment]
thank you sir

**Comment by xuv** [comment]
This was apparently part of an abuse of Utopian platform. So closing it. More info in this article: https://steemit.com/utopian-io/@xuv/utopian-io-is-breaking-the-open-source-contribution-model-and-needs-to-be-fixed
