### ISSUE TITLE
Tagalog Translation

### ISSUE THREAD

**Issue by themarshann** [libreobjet/open-guide#23]
Hi, can I possibly contribute for this project by translating this guide into Tagalog? Thanks!

**Comment by xuv** [comment]
@themashann: Sure. You are welcome to make a translation in Tagalog. 

Though I'd like to inform you that I will have to find a person to read your submissions before accepting any pull request.

Have a nice day.

**Comment by themarshann** [comment]
Okay. Thanks :)

**Comment by xuv** [comment]
This was apparently part of an abuse of Utopian platform. So closing it. More info in this article: https://steemit.com/utopian-io/@xuv/utopian-io-is-breaking-the-open-source-contribution-model-and-needs-to-be-fixed
